#!/usr/bin/env bash
set -e
set -o pipefail

if [ "$BENCH" = 'false' ]; then
    echo "Skipping bench(BENCH=$BENCH)"
    exit 0
fi

HERE=$(dirname $(readlink -f $0))
cd $HERE/..

python --version
filename=bench/log/`date +%F_%T`.txt

rm -rf venv-bench
virtualenv venv-bench
. venv-bench/bin/activate
CHEETAH_C_EXT=true pip install .
python ./bench/_runbench.py | tee -a "$filename"
